server:
  port: 8081
  http2:
    enabled: true
  tomcat:
    max-threads: 10
    accept-count: 10
    max-connections: 10

servlet:
  session:
    persistent: true




spring:
  output:
    ansi:
      enabled: ALWAYS
  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
    check-template: true
    check-template-location: true
    encoding: UTF-8
    mode: HTML
  data:
    mongodb:
      host: localhost
      port: 37017
      database: ivector-dev
